services:
  auth:
    #image: minjooong/msa-kitcha-auth
    image: 502744150367.dkr.ecr.us-west-2.amazonaws.com/kitcha-registry:auth-latest
    #build:
    #  context: https://github.com/MSA-Kitcha/MSA-Kitcha-Authentication.git
    environment:
      MYSQL_DATABASE: ${MYSQL_USER_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_EXPIRATION_TIME: ${TOKEN_EXPIRATION_TIME}
      TEST_USER_PASSWORD: ${TEST_USER_PASSWORD}
      TEST_ADMIN_PASSWORD: ${TEST_ADMIN_PASSWORD}
    container_name: auth
    networks:
      - kitcha_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8091:8091"
    restart: on-failure

  article:
    #image: minjooong/msa-kitcha-article
    image: 502744150367.dkr.ecr.us-west-2.amazonaws.com/kitcha-registry:article-latest
    #build:
    #  context: https://github.com/MSA-Kitcha/MSA-Kitcha-Article.git
    environment:
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      GROQ_API_KEY: ${GROQ_API_KEY}
    container_name: article
    networks:
      - kitcha_network
    ports:
      - "8092:8080"
    restart: on-failure

  board:
    #image: minjooong/msa-kitcha-board
    image: 502744150367.dkr.ecr.us-west-2.amazonaws.com/kitcha-registry:board-latest
    #build:
    #  context: https://github.com/MSA-Kitcha/MSA-Kitcha-Board.git
    environment:
      MYSQL_DATABASE: ${MYSQL_BOARD_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: board
    networks:
      - kitcha_network
    ports:
      - "8093:8080"
    restart: on-failure

volumes:
  mysql_data:

networks:
  kitcha_network:
